import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Head from "next/head";
import Slider from "@/components/Slider/Slider";
import Categories from "@/components/Categories/Categories";
import CountDown from "@/components/CountDown/CountDown";
import Courses from "@/components/Courses/Courses";
import Team from "@/components/Team/Team";
import BackToTop from "@/components/BackToTop/BackToTop";
import Blog from "@/components/Blog/Blog";
import About from "@/components/About/About";
import Testimonials from "@/components/Testimonials/Testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Education | Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Slider />
        <Categories />
        <CountDown />
        <Courses />
        <Team />
        <About />
        <Testimonials />
        <Blog />
      </main>
      <Footer />
      <BackToTop />
    </>
  );
}
